-- MySQL Script generated by MySQL Workbench
-- Wed Sep 11 11:13:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema organeasy_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `organeasy_db` ;

-- -----------------------------------------------------
-- Schema organeasy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `organeasy_db` DEFAULT CHARACTER SET utf8 ;
USE `organeasy_db` ;

-- -----------------------------------------------------
-- Table `organeasy_db`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`Aluno` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `id_avatar` INT UNSIGNED NULL,
  `criado_em` DATETIME NULL,
  `atualizado_em` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_avatar_idx` (`id_avatar` ASC) VISIBLE,
  CONSTRAINT `fk_avatarAluno`
    FOREIGN KEY (`id_avatar`)
    REFERENCES `organeasy_db`.`Avatar` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organeasy_db`.`Atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`Atividade` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`Atividade` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `concluida` TINYINT NULL DEFAULT 0,
  `data_entrega` DATETIME NULL,
  `criado_em` DATETIME NULL,
  `atualizado_em` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organeasy_db`.`AtividadeCurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`AtividadeCurso` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`AtividadeCurso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_curso` INT UNSIGNED NOT NULL,
  `id_atividade` INT UNSIGNED NOT NULL,
  `tem_pontos` TINYINT NOT NULL,
  `valor` DOUBLE NULL,
  `valor_ganho` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cursoAtividade_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_atividadeAtividade_idx` (`id_atividade` ASC) VISIBLE,
  CONSTRAINT `fk_cursoAtividade`
    FOREIGN KEY (`id_curso`)
    REFERENCES `organeasy_db`.`Curso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_atividadeAtividade`
    FOREIGN KEY (`id_atividade`)
    REFERENCES `organeasy_db`.`Atividade` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organeasy_db`.`AtividadeLazer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`AtividadeLazer` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`AtividadeLazer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_atividade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_atividadeAtividadeL_idx` (`id_atividade` ASC) VISIBLE,
  CONSTRAINT `fk_atividadeAtividadeL`
    FOREIGN KEY (`id_atividade`)
    REFERENCES `organeasy_db`.`Atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organeasy_db`.`AtividadeMateria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`AtividadeMateria` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`AtividadeMateria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_materia` INT UNSIGNED NOT NULL,
  `id_atividade` INT UNSIGNED NOT NULL,
  `tem_pontos` TINYINT NOT NULL,
  `valor` DOUBLE NULL,
  `valor_ganho` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_materiaAtividade_idx` (`id_materia` ASC) VISIBLE,
  INDEX `fk_atividadeAtividadeM_idx` (`id_atividade` ASC) VISIBLE,
  CONSTRAINT `fk_materiaAtividade`
    FOREIGN KEY (`id_materia`)
    REFERENCES `organeasy_db`.`Materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividadeAtividadeM`
    FOREIGN KEY (`id_atividade`)
    REFERENCES `organeasy_db`.`Atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organeasy_db`.`Avatar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`Avatar` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`Avatar` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NULL,
  `atualizado_em` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organeasy_db`.`Checklist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`Checklist` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`Checklist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_atividade` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NULL,
  `atualizado_em` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_atividadeChecklist_idx` (`id_atividade` ASC) VISIBLE,
  CONSTRAINT `fk_atividadeChecklist`
    FOREIGN KEY (`id_atividade`)
    REFERENCES `organeasy_db`.`Atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organeasy_db`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`Curso` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`Curso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tem_materias` TINYINT NOT NULL,
  `criado_em` DATETIME NULL,
  `atualizado_em` DATETIME NULL,
  `id_aluno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_aluno_idx` (`id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_alunoCurso`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `organeasy_db`.`Aluno` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organeasy_db`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`Materia` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`Materia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_curso` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NULL,
  `atualizado_em` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_curso_idx` (`id_curso` ASC) VISIBLE,
  UNIQUE INDEX `id_curso_UNIQUE` (`id_curso` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_cursoMateria`
    FOREIGN KEY (`id_curso`)
    REFERENCES `organeasy_db`.`Curso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organeasy_db`.`OpcaoChecklist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organeasy_db`.`OpcaoChecklist` ;

CREATE TABLE IF NOT EXISTS `organeasy_db`.`OpcaoChecklist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_checklist` INT UNSIGNED NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `feito` TINYINT NULL DEFAULT 0,
  `criado_em` DATETIME NULL,
  `atualizado_em` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_checklistOpcao_idx` (`id_checklist` ASC) VISIBLE,
  CONSTRAINT `fk_checklistOpcao`
    FOREIGN KEY (`id_checklist`)
    REFERENCES `organeasy_db`.`Checklist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
